In [8]:
list1=['apple','banana','cherry']
list2=[1,5,7,9,3]
list3=[True, False, False]

print(list1)
print(list2)
print(list3)

['apple', 'banana', 'cherry']
[1, 5, 7, 9, 3]
[True, False, False]


In [9]:
thislist=['apple','banana','cherry']
print(thislist[0])
print(thislist[-1])
print(thislist[-2])

apple
cherry
banana


In [10]:
thislist=['apple','banana','cherry','orange','kiwi','melon','melon']
print(thislist[2:5])
print(thislist[2:-2])

['cherry', 'orange', 'kiwi']
['cherry', 'orange', 'kiwi']


In [12]:
thislist=['apple','banana','cherry']
thislist.append('orange')
print(thislist)

['apple', 'banana', 'cherry', 'orange']


In [13]:
thislist=['apple','banana','cherry']
tropical=['mango','pinapple','papaya']
thislist.extend(tropical)
print(thislist)

['apple', 'banana', 'cherry', 'mango', 'pinapple', 'papaya']


In [15]:
thislist=['apple','banana','cherry']
thislist.remove('banana')
print(thislist)

['apple', 'cherry']


In [20]:
thislist=['apple','banana','cherry']
for x in thislist:
    print(x)

apple
banana
cherry


In [19]:
thislist=['apple','banana','cherry']
for i in range(len(thislist)):
    print(thislist[i])

apple
banana
cherry


In [24]:
thistuple=('apple','banana','cherry','apple','cherry')
print(thistuple)

('apple', 'banana', 'cherry', 'apple', 'cherry')


In [23]:
thistuple=('apple','banana','cherry','orange','kiwi','melon','mango')
print(thistuple[1])
print(thistuple[-1])
print(thistuple[2:5])

banana
mango
('cherry', 'orange', 'kiwi')


In [27]:
fruits=('apple','banana','cherry')
(green,yellow,red)=fruits

print(green)
print(yellow)
print(red)

apple
banana
cherry


In [28]:
thistuple=('apple','banana','cherry')
for x in thistuple:
    print(x)

apple
banana
cherry


In [29]:
thistuple=('apple','banana','cherry')
for i in range(len(thistuple)):
    print(thistuple[i])

apple
banana
cherry


In [30]:
thisdict= {
    'brand': 'Ford',
    'model': 'Mustang',
    'year': 1964
}
print(thisdict)
print(thisdict['brand'])

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Ford


In [31]:
thisdict= {
    'brand': 'Ford',
    'model': 'Mustang',
    'year': 1964
}

x = thisdict.keys()
print(x)

y = thisdict.values()
print(y)

z = thisdict.items()
print(z)

dict_keys(['brand', 'model', 'year'])
dict_values(['Ford', 'Mustang', 1964])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])


In [32]:
thisdict= {
    'brand': 'Ford',
    'model': 'Mustang',
    'year': 1964
}
thisdict['color']='red'
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}


In [33]:
thisdict= {
    'brand': 'Ford',
    'model': 'Mustang',
    'year': 1964
}
thisdict.update({'year':2021})
print(thisdict)

thisdict.update({'color':'red'})
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2021}
{'brand': 'Ford', 'model': 'Mustang', 'year': 2021, 'color': 'red'}


In [34]:
thisdict= {
    'brand': 'Ford',
    'model': 'Mustang',
    'year': 1964
}
thisdict.pop('model')
print(thisdict)

{'brand': 'Ford', 'year': 1964}


In [35]:
thisdict= {
    'brand': 'Ford',
    'model': 'Mustang',
    'year': 1964
}
print('==keys==')
for x in thisdict.keys():
    print(x)
    
print('==values==')
for x in thisdict.values():
    print(x)
    
print('==items==')
for x,y in thisdict.items():
    print(x,y)

==keys==
brand
model
year
==values==
Ford
Mustang
1964
==items==
brand Ford
model Mustang
year 1964


# Part 2. Vector and Matrix

In [40]:
import numpy as np
import pandas as pd

# Load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# Convert a pandas dataframe into a numpy array
x = df.values[:,1:-1]
print(type(x))
print(x.shape)
print(x)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


In [43]:
# Get first row and the second to law row
x1=x[0,:]
x2=x[-1,:]

print(x1)
print(x2)

# Addition
y=x1+x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[31.0 4 119.0 82 2720 19.4 82]
[49.0 12 426.0 212 6224 31.4 152]


In [ ]:
# Get first 5 rows and last 5 rows
m1=x[0:5,:]
m2=x[-5:,:]